api_platform:
    title: Hello API Platform
    version: 1.0.0
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    eager_loading:
        max_joins: 30
        fetch_partial: true
        force_eager: false
    defaults:
        pagination_client_items_per_page: true
        pagination_items_per_page: 30
        pagination_maximum_items_per_page: 50
        normalization_context:
            groups: ['read']
        denormalization_context:
            groups: ['write']
        stateless: false
        cache_headers:
            max_age: 0
            shared_max_age: 3600
            vary: ['Content-Type', 'Authorization', 'Origin']
            public: true
    collection:
        pagination:
            enabled: true
            enabled_parameter_name: 'pagination'
            items_per_page_parameter_name: 'itemsPerPage'
            page_parameter_name: 'page'
            partial_parameter_name: 'partial'
