// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig, env } from "prisma/config";

// Load environment variables from .env.local if present (local dev)
if (process.env.NODE_ENV !== "production") {
  config({ path: ".env.local" });
}
config();

// Validation des variables critiques pour le déploiement
if (process.env.VERCEL && !process.env.DIRECT_URL) {
  console.warn(
    "⚠️ [Prisma Config] DIRECT_URL est manquante sur Vercel. Le build risque d'échouer lors de 'prisma migrate deploy'."
  );
}

export default defineConfig({
  schema: "prisma/schema",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    /**
     * Pour Prisma 7, l'URL définie ici est utilisée par la CLI (migration, introspection).
     * On utilise DIRECT_URL pour permettre les advisory locks sur Supabase.
     * Le client (runtime) utilisera DATABASE_URL par défaut depuis l'environnement.
     */
    url:
      process.env.DIRECT_URL ||
      "postgres://DIRECT_URL_MISSING_ON_VERCEL@localhost:5432/db",
    // Shadow database only needed for `migrate dev` locally
    shadowDatabaseUrl:
      process.env.NODE_ENV === "development"
        ? "postgresql://postgres:postgres@127.0.0.1:54322/prisma_shadow"
        : undefined,
  },
});
